### ISSUE TITLE
RBDDimmer fails to compile on ESP32 core 3.1.3 – timerBegin / timerAttachInterrupt signatures changed

### ISSUE THREAD

**Issue by sajedhm** [qppd/RobotDyn-Dimmer#1]
c:\Users\dev\Documents\Arduino\libraries\RBDDimmer\RBDDimmer.cpp: In member function 'void RBDDimmer::begin(rbd_dimmer_mode_t, rbd_dimmer_state_t)':
c:\Users\dev\Documents\Arduino\libraries\RBDDimmer\RBDDimmer.cpp:61:28: error: too many arguments to function 'hw_timer_t* timerBegin(uint32_t)'
   61 |         _timer = timerBegin(0, RBD_DIMMER_TIMER_DIVIDER, true);
      |                  ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:\Users\dev\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.1.3\cores\esp32/esp32-hal.h:98,
                 from C:\Users\dev\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.1.3\cores\esp32/Arduino.h:45,
                 from c:\Users\dev\Documents\Arduino\libraries\RBDDimmer\RBDDimmer.h:4,
                 from c:\Users\dev\Documents\Arduino\libraries\RBDDimmer\RBDDimmer.cpp:2:
C:\Users\dev\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.1.3\cores\esp32/esp32-hal-timer.h:35:13: note: declared here
   35 | hw_timer_t *timerBegin(uint32_t frequency);
      |             ^~~~~~~~~~
c:\Users\dev\Documents\Arduino\libraries\RBDDimmer\RBDDimmer.cpp:62:29: error: too many arguments to function 'void timerAttachInterrupt(hw_timer_t*, void (*)())'
   62 |         timerAttachInterrupt(_timer, &RBDDimmer_onTimerISR, true);
      |         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\dev\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.1.3\cores\esp32/esp32-hal-timer.h:50:6: note: declared here
   50 | void timerAttachInterrupt(hw_timer_t *timer, void (*userFunc)(void));
      |      ^~~~~~~~~~~~~~~~~~~~
c:\Users\dev\Documents\Arduino\libraries\RBDDimmer\RBDDimmer.cpp:63:9: error: 'timerAlarmWrite' was not declared in this scope; did you mean 'timerWrite'?
   63 |         timerAlarmWrite(_timer, RBD_DIMMER_TIMER_ALARM_US, true);
      |         ^~~~~~~~~~~~~~~
      |         timerWrite
c:\Users\dev\Documents\Arduino\libraries\RBDDimmer\RBDDimmer.cpp:64:9: error: 'timerAlarmEnable' was not declared in this scope; did you mean 'timerAlarm'?
   64 |         timerAlarmEnable(_timer);
      |         ^~~~~~~~~~~~~~~~
      |         timerAlarm
c:\Users\dev\Documents\Arduino\libraries\RBDDimmer\RBDDimmer.cpp: In function 'void RBDDimmer_onTimerISR()':
c:\Users\dev\Documents\Arduino\libraries\RBDDimmer\RBDDimmer.cpp:146:43: error: 'int RBDDimmer::_outputPin' is private within this context
  146 |                 digitalWrite(_dimmers[k]->_outputPin, HIGH);
      |                                           ^~~~~~~~~~
c:\Users\dev\Documents\Arduino\libraries\RBDDimmer\RBDDimmer.h:32:9: note: declared private here
   32 |     int _outputPin;
      |         ^~~~~~~~~~
c:\Users\dev\Documents\Arduino\libraries\RBDDimmer\RBDDimmer.cpp:149:43: error: 'int RBDDimmer::_outputPin' is private within this context
  149 |                 digitalWrite(_dimmers[k]->_outputPin, LOW);
      |                                           ^~~~~~~~~~
c:\Users\dev\Documents\Arduino\libraries\RBDDimmer\RBDDimmer.h:32:9: note: declared private here
   32 |     int _outputPin;
      |         ^~~~~~~~~~
exit status 1

Compilation error: exit status 1

**Comment by qppd** [comment]
The code has been updated to fix the ESP32 timer API usage and to add a public getter for [_outputPin](vscode-file://vscode-app/c:/Users/sajed/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html), resolving the compilation errors you reported.

What was changed:

Updated the timer function calls to match the new ESP32 API.
Added a getOutputPin() public method in [RBDDimmer](vscode-file://vscode-app/c:/Users/sajed/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) and used it in the ISR.
You may need to further adjust or uncomment the timerAlarmWrite and timerAlarmEnable lines if your ESP32 core version supports them.
